application: blablastar-alecdotico
version: '1'
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

- url: .*
  script: main.app


