application: blablastar-alecdotico
version: '1'
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /fonts
  static_dir: templates/fonts

- url: .*
  script: main.app


